// Modulo principal

#include "../include/dialogs" // definindo os dialogs
#include "../include/defines" // definindo variaveis
#include "../include/variaveis" // definindo variaveis
#include "../include/funcoes" // definindo variaveis
#include "../include/player" // funcoes dos players
#include "../include/login" // sistema de login e registro
#include "../include/voip" // totalmente opcional, caso n quiser usar basta comentar essa linha
#include "../include/velocimetro" // totalmente opcional, caso n quiser usar basta comentar essa linha
#include "../include/fomeesede" // totalmente opcional, caso n quiser usar basta comentar essa linha
#include "../include/comandos/main" // comandos

// para adicionar um novo modulo
//#include "../include/nome do modulo aqui" // 

// para adicionar um novo modulo de comandos edite o comandos>main.inc
